# File: .github/workflows/repo-sync.yml
name: "sync"
on:
  push:
    branches:
    - sync
  schedule:
  - cron:  "0 21 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://r8.googlesource.com/r8"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.GITHUB_TOKEN }}
